from typing import Any, Optional, Protocol


class BaseEmbeddingProvider(Protocol):
    """Protocol defining the standard interface for embedding providers (OpenAI, Gemini, Mock)."""

    async def embed(self, text: str, credentials: Optional[dict[str, Any]] = None) -> list[float]:
        """Generates embedding vector for a single text chunk."""
        ...

    async def batch_embed(self, texts: list[str], credentials: Optional[dict[str, Any]] = None) -> list[list[float]]:
        """Generates embedding vectors for a list of text chunks in parallel."""
        ...

    async def dimensions(self) -> int:
        """Returns the dimensions of the vectors generated by the default model of this provider."""
        ...

    async def health_check(self, credentials: Optional[dict[str, Any]] = None) -> bool:
        """Verifies API connection credentials health state."""
        ...
