"""sprint_7a_distributed

Revision ID: 42858e8eddaf
Revises: e73028902f64
Create Date: 2026-07-18 22:47:12.044202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42858e8eddaf'
down_revision: Union[str, Sequence[str], None] = 'e73028902f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_job_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_job_events_job_id'), 'ai_job_events', ['job_id'], unique=False)
    op.create_table('ai_workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=False),
    sa.Column('worker_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'IDLE', 'BUSY', 'DRAINING', 'OFFLINE', name='worker_status', native_enum=False), nullable=False),
    sa.Column('supported_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_parallel_jobs', sa.Integer(), nullable=False),
    sa.Column('current_job_id', sa.UUID(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('running_jobs', sa.Integer(), nullable=False),
    sa.Column('queue_latency', sa.Float(), nullable=False),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=False),
    sa.Column('shutdown_reason', sa.String(length=200), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'DISPATCHED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', 'DEAD_LETTER', name='ai_job_status', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.Enum('DEFAULT', 'PRIORITY', 'LONG_RUNNING', 'RETRY', 'DEAD_LETTER', 'SALES', 'MARKETING', 'ANALYTICS', name='queue_type', native_enum=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('client_version', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('request_hash', sa.String(length=255), nullable=True),
    sa.Column('execution_trace_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_budget', sa.Integer(), nullable=False),
    sa.Column('retry_consumed', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['ai_workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_idempotency_key'), 'ai_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_ai_jobs_organization_id'), 'ai_jobs', ['organization_id'], unique=False)
    op.create_table('ai_job_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'DISPATCHED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', 'DEAD_LETTER', name='ai_job_status', native_enum=False), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(length=250), nullable=True),
    sa.Column('failure_category', sa.Enum('LLM_ERROR', 'TOOL_ERROR', 'TIMEOUT', 'VALIDATION', 'SYSTEM', name='job_failure_category', native_enum=False), nullable=True),
    sa.Column('last_exception', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_job_results_job_id'), 'ai_job_results', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_job_results_job_id'), table_name='ai_job_results')
    op.drop_table('ai_job_results')
    op.drop_index(op.f('ix_ai_jobs_organization_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_idempotency_key'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    op.drop_table('ai_workers')
    op.drop_index(op.f('ix_ai_job_events_job_id'), table_name='ai_job_events')
    op.drop_table('ai_job_events')
    # ### end Alembic commands ###
