"""sprint_6a_observability

Revision ID: 5199a22d5035
Revises: da0beea601de
Create Date: 2026-07-18 14:27:32.420491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5199a22d5035'
down_revision: Union[str, Sequence[str], None] = 'da0beea601de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_execution_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Enum('SALES', 'BUSINESS_ANALYST', 'MARKETING', 'SUPPORT', 'RECRUITER', 'FINANCE', 'HUMAN', name='agent_type', native_enum=False), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'SUCCESS', 'FAILED', 'CANCELLED', name='trace_status', native_enum=False), nullable=False),
    sa.Column('sampling_mode', sa.Enum('FULL', 'HEAD', 'DISABLED', name='trace_sampling_mode', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_execution_traces_conversation_id'), 'ai_execution_traces', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_execution_traces_organization_id'), 'ai_execution_traces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_execution_traces_trace_id'), 'ai_execution_traces', ['trace_id'], unique=False)
    op.create_table('ai_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_trace_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('SALES', 'BUSINESS_ANALYST', 'MARKETING', 'SUPPORT', 'RECRUITER', 'FINANCE', 'HUMAN', name='agent_type', native_enum=False), nullable=False),
    sa.Column('metric_type', sa.Enum('LATENCY', 'TOKEN', 'COST', 'MEMORY', 'RETRIEVAL', 'TOOL', 'PLANNING', 'POLICY', name='metric_type', native_enum=False), nullable=False),
    sa.Column('value_ms', sa.Integer(), nullable=True),
    sa.Column('value_tokens', sa.Integer(), nullable=True),
    sa.Column('value_cost', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_metrics_agent_type'), 'ai_metrics', ['agent_type'], unique=False)
    op.create_index(op.f('ix_ai_metrics_execution_trace_id'), 'ai_metrics', ['execution_trace_id'], unique=False)
    op.create_index(op.f('ix_ai_metrics_organization_id'), 'ai_metrics', ['organization_id'], unique=False)
    op.create_table('ai_planning_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planner_version', sa.String(length=20), nullable=True),
    sa.Column('planning_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_planning_traces_execution_trace_id'), 'ai_planning_traces', ['execution_trace_id'], unique=False)
    op.create_table('ai_policy_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('policy', sa.String(length=200), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('risk', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_policy_traces_execution_trace_id'), 'ai_policy_traces', ['execution_trace_id'], unique=False)
    op.create_table('ai_prompt_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('compiled_prompt', sa.Text(), nullable=True),
    sa.Column('variables_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prompt_traces_execution_trace_id'), 'ai_prompt_traces', ['execution_trace_id'], unique=False)
    op.create_table('ai_reasoning_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('risk', sa.String(length=50), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reasoning_traces_execution_trace_id'), 'ai_reasoning_traces', ['execution_trace_id'], unique=False)
    op.create_table('ai_retrieval_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('retrieved_memories_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_knowledge_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_crm_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vector_hit_count', sa.Integer(), nullable=True),
    sa.Column('memory_latency_ms', sa.Integer(), nullable=True),
    sa.Column('crm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('knowledge_latency_ms', sa.Integer(), nullable=True),
    sa.Column('vector_search_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_retrieval_latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_retrieval_traces_execution_trace_id'), 'ai_retrieval_traces', ['execution_trace_id'], unique=False)
    op.create_table('ai_tool_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_trace_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=200), nullable=False),
    sa.Column('arguments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUCCESS', 'FAILED', 'CANCELLED', name='trace_status', native_enum=False), nullable=False),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_traces_execution_trace_id'), 'ai_tool_traces', ['execution_trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tool_traces_execution_trace_id'), table_name='ai_tool_traces')
    op.drop_table('ai_tool_traces')
    op.drop_index(op.f('ix_ai_retrieval_traces_execution_trace_id'), table_name='ai_retrieval_traces')
    op.drop_table('ai_retrieval_traces')
    op.drop_index(op.f('ix_ai_reasoning_traces_execution_trace_id'), table_name='ai_reasoning_traces')
    op.drop_table('ai_reasoning_traces')
    op.drop_index(op.f('ix_ai_prompt_traces_execution_trace_id'), table_name='ai_prompt_traces')
    op.drop_table('ai_prompt_traces')
    op.drop_index(op.f('ix_ai_policy_traces_execution_trace_id'), table_name='ai_policy_traces')
    op.drop_table('ai_policy_traces')
    op.drop_index(op.f('ix_ai_planning_traces_execution_trace_id'), table_name='ai_planning_traces')
    op.drop_table('ai_planning_traces')
    op.drop_index(op.f('ix_ai_metrics_organization_id'), table_name='ai_metrics')
    op.drop_index(op.f('ix_ai_metrics_execution_trace_id'), table_name='ai_metrics')
    op.drop_index(op.f('ix_ai_metrics_agent_type'), table_name='ai_metrics')
    op.drop_table('ai_metrics')
    op.drop_index(op.f('ix_ai_execution_traces_trace_id'), table_name='ai_execution_traces')
    op.drop_index(op.f('ix_ai_execution_traces_organization_id'), table_name='ai_execution_traces')
    op.drop_index(op.f('ix_ai_execution_traces_conversation_id'), table_name='ai_execution_traces')
    op.drop_table('ai_execution_traces')
    # ### end Alembic commands ###
