"""sprint_2c_request_context

Revision ID: 53085cb11e30
Revises: 76f81339a2b4
Create Date: 2026-07-12 19:00:05.494668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53085cb11e30'
down_revision: Union[str, Sequence[str], None] = '76f81339a2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'SUSPENDED', 'EXPIRED', name='organization_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('organization_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'SALES', 'VIEWER', name='organization_role', native_enum=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'CANCELLED', 'EXPIRED', name='invitation_status', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_invitations_email', 'organization_invitations', ['email'], unique=False)
    op.create_index('ix_org_invitations_status', 'organization_invitations', ['status'], unique=False)
    op.create_index('ix_org_invitations_token_hash', 'organization_invitations', ['token_hash'], unique=False)
    op.create_index('uq_org_invitations_pending_email', 'organization_invitations', ['organization_id', 'email'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'SALES', 'VIEWER', name='organization_role', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='member_status', native_enum=False), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member_org_user')
    )
    op.create_table('organization_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_signature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.add_column('login_audit_logs', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('login_audit_logs', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'login_audit_logs', 'user_sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.add_column('user_sessions', sa.Column('jti', sa.String(length=36), nullable=False))
    op.add_column('user_sessions', sa.Column('token_hash', sa.String(length=64), nullable=False))
    op.add_column('user_sessions', sa.Column('active_organization_id', sa.UUID(), nullable=True))
    op.add_column('user_sessions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('user_sessions', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['jti'], unique=True)
    op.create_foreign_key(None, 'user_sessions', 'organizations', ['active_organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_jti'), table_name='user_sessions')
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'expires_at')
    op.drop_column('user_sessions', 'ip_address')
    op.drop_column('user_sessions', 'active_organization_id')
    op.drop_column('user_sessions', 'token_hash')
    op.drop_column('user_sessions', 'jti')
    op.drop_constraint(None, 'login_audit_logs', type_='foreignkey')
    op.drop_column('login_audit_logs', 'event_metadata')
    op.drop_column('login_audit_logs', 'session_id')
    op.drop_table('organization_settings')
    op.drop_table('organization_members')
    op.drop_index('uq_org_invitations_pending_email', table_name='organization_invitations', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_org_invitations_token_hash', table_name='organization_invitations')
    op.drop_index('ix_org_invitations_status', table_name='organization_invitations')
    op.drop_index('ix_org_invitations_email', table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
