"""sprint_4b_scheduler_and_reminders

Revision ID: 6ef26d5c6ccb
Revises: d32d159ee75a
Create Date: 2026-07-13 00:47:05.318601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ef26d5c6ccb'
down_revision: Union[str, Sequence[str], None] = 'd32d159ee75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('recipient_type', sa.Enum('USER', 'EMAIL', 'PHONE', 'GROUP', name='recipient_type', native_enum=False), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', name='notification_channel', native_enum=False), nullable=False),
    sa.Column('provider', sa.Enum('SMTP', 'SES', 'SENDGRID', 'TWILIO', 'META', 'GUPSHUP', name='notification_provider', native_enum=False), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notification_priority', native_enum=False), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', name='notification_status', native_enum=False), nullable=False),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_queue_scheduled', 'notification_queue', ['scheduled_at'], unique=False, postgresql_where=sa.text("status = 'QUEUED'"))
    op.create_index('uq_notification_idempotency', 'notification_queue', ['organization_id', 'idempotency_key'], unique=True)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('LEAD', 'TASK', name='entity_type', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.Enum('INACTIVITY', 'DUE_TASK', 'FOLLOW_UP', 'BIRTHDAY', name='reminder_type', native_enum=False), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'DISMISSED', 'FAILED', name='reminder_status', native_enum=False), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_type', sa.Enum('USER', 'SYSTEM', 'AI', 'WEBHOOK', name='actor_type', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_org_entity', 'reminders', ['organization_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_reminders_remind_at', 'reminders', ['remind_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index('uq_pending_reminders', 'reminders', ['organization_id', 'entity_type', 'entity_id', 'reminder_type'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.Enum('GENERATE_REMINDERS', 'PROCESS_REMINDERS', 'SEND_QUEUED_NOTIFICATIONS', 'SYSTEM_PRUNE_LOGS', name='job_type', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_version', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISABLED', 'SYSTEM', name='job_status', native_enum=False), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_jobs_next_run_at', 'scheduled_jobs', ['next_run_at'], unique=False, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('ix_scheduled_jobs_organization_id', 'scheduled_jobs', ['organization_id'], unique=False)
    op.create_table('job_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'RETRYING', 'FAILED', 'DEAD_LETTER', name='job_execution_status', native_enum=False), nullable=False),
    sa.Column('execution_key', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scheduler_instance', sa.String(length=100), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=False),
    sa.Column('created_reminders', sa.Integer(), nullable=False),
    sa.Column('published_events', sa.Integer(), nullable=False),
    sa.Column('queued_notifications', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scheduled_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_job_executions_key', 'job_executions', ['job_id', 'execution_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_job_executions_key', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index('ix_scheduled_jobs_organization_id', table_name='scheduled_jobs')
    op.drop_index('ix_scheduled_jobs_next_run_at', table_name='scheduled_jobs', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('scheduled_jobs')
    op.drop_index('uq_pending_reminders', table_name='reminders', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_reminders_remind_at', table_name='reminders', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_reminders_org_entity', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('uq_notification_idempotency', table_name='notification_queue')
    op.drop_index('ix_notification_queue_scheduled', table_name='notification_queue', postgresql_where=sa.text("status = 'QUEUED'"))
    op.drop_table('notification_queue')
    # ### end Alembic commands ###
