"""add_sessions_roles_audit_logs_and_locking

Revision ID: 76f81339a2b4
Revises: 34de88f32e55
Create Date: 2026-07-09 18:34:54.449483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f81339a2b4'
down_revision: Union[str, Sequence[str], None] = '34de88f32e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the user_role PostgreSQL enum type
    user_role_enum = sa.Enum('OWNER', 'ADMIN', 'SALES', 'VIEWER', name='user_role')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_audit_logs_email'), 'login_audit_logs', ['email'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('refresh_tokens', sa.Column('replaced_by', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'SALES', 'VIEWER', name='user_role'), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'role')
    op.drop_column('refresh_tokens', 'replaced_by')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_login_audit_logs_email'), table_name='login_audit_logs')
    op.drop_table('login_audit_logs')
    # ### end Alembic commands ###

    # Drop the user_role PostgreSQL enum type
    user_role_enum = sa.Enum('OWNER', 'ADMIN', 'SALES', 'VIEWER', name='user_role')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
