"""sprint_4c_communication_foundation

Revision ID: 77b8290f69cb
Revises: 6ef26d5c6ccb
Create Date: 2026-07-13 14:45:45.490555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77b8290f69cb'
down_revision: Union[str, Sequence[str], None] = '6ef26d5c6ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('SMTP', 'GMAIL', 'SES', 'META', 'TWILIO', 'MSG91', 'MOCK', name='provider_type', native_enum=False), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', name='communication_channel', native_enum=False), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('credentials_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_default_provider_channel', 'communication_providers', ['organization_id', 'channel'], unique=True, postgresql_where='is_default = true AND enabled = true')
    op.create_table('communication_templates',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', name='communication_channel', native_enum=False), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('variables_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_communication_templates', 'communication_templates', ['organization_id', 'name', 'channel'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', name='communication_channel', native_enum=False), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('recipient_type', sa.Enum('USER', 'EMAIL', 'PHONE', 'GROUP', 'LEAD', 'RAW', name='recipient_type', native_enum=False), nullable=False),
    sa.Column('direction', sa.Enum('OUTBOUND', 'INBOUND', name='communication_direction', native_enum=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('parent_communication_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('rendered_subject', sa.String(length=255), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=True),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'SENT', 'DELIVERED', 'FAILED', 'CANCELLED', name='communication_status', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='communication_priority', native_enum=False), nullable=False),
    sa.Column('render_engine_version', sa.SmallInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['communication_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['communication_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_communications_conversation', 'communications', ['conversation_id'], unique=False)
    op.create_index('ix_communications_scheduled', 'communications', ['scheduled_at'], unique=False, postgresql_where="status = 'QUEUED'")
    op.create_index('uq_communication_idempotency', 'communications', ['organization_id', 'idempotency_key'], unique=True)
    op.create_table('communication_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('communication_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.Enum('QUEUED', 'PROCESSING', 'SENT', 'DELIVERED', 'FAILED', 'BOUNCED', 'OPENED', 'CLICKED', 'READ', 'DELIVERY_UNKNOWN', 'UNSUBSCRIBED', 'SPAM_REPORTED', 'REJECTED', name='delivery_event', native_enum=False), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('provider_latency_ms', sa.Integer(), nullable=True),
    sa.Column('provider_status_code', sa.Integer(), nullable=True),
    sa.Column('provider_error_code', sa.String(length=50), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_deliveries')
    op.drop_index('uq_communication_idempotency', table_name='communications')
    op.drop_index('ix_communications_scheduled', table_name='communications', postgresql_where="status = 'QUEUED'")
    op.drop_index('ix_communications_conversation', table_name='communications')
    op.drop_table('communications')
    op.drop_index('uq_communication_templates', table_name='communication_templates', postgresql_where='deleted_at IS NULL')
    op.drop_table('communication_templates')
    op.drop_index('uq_default_provider_channel', table_name='communication_providers', postgresql_where='is_default = true AND enabled = true')
    op.drop_table('communication_providers')
    # ### end Alembic commands ###
