"""sprint_7b_event_bus

Revision ID: 9bbbd28b17b0
Revises: 42858e8eddaf
Create Date: 2026-07-18 23:08:45.670858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bbbd28b17b0'
down_revision: Union[str, Sequence[str], None] = '42858e8eddaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_event_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscriber_name', sa.String(length=100), nullable=False),
    sa.Column('subscriber_version', sa.String(length=20), nullable=False),
    sa.Column('handler_version', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.Enum('JOB_CREATED', 'JOB_STARTED', 'JOB_COMPLETED', 'TRACE_CREATED', 'EVALUATION_COMPLETED', 'LEARNING_DATASET_CREATED', 'LEARNING_SUGGESTION_CREATED', 'WORKFLOW_STARTED', 'WORKFLOW_COMPLETED', 'CAMPAIGN_STARTED', 'CAMPAIGN_COMPLETED', name='event_type', native_enum=False), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('retry_limit', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_event_subscriptions_event_type'), 'ai_event_subscriptions', ['event_type'], unique=False)
    op.create_table('ai_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('JOB_CREATED', 'JOB_STARTED', 'JOB_COMPLETED', 'TRACE_CREATED', 'EVALUATION_COMPLETED', 'LEARNING_DATASET_CREATED', 'LEARNING_SUGGESTION_CREATED', 'WORKFLOW_STARTED', 'WORKFLOW_COMPLETED', 'CAMPAIGN_STARTED', 'CAMPAIGN_COMPLETED', name='event_type', native_enum=False), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=True),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'RETRYING', 'DEAD_LETTER', name='event_status', native_enum=False), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_ai_events_aggregate_id'), 'ai_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_ai_events_aggregate_type'), 'ai_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_ai_events_causation_id'), 'ai_events', ['causation_id'], unique=False)
    op.create_index(op.f('ix_ai_events_correlation_id'), 'ai_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ai_events_event_type'), 'ai_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ai_events_organization_id'), 'ai_events', ['organization_id'], unique=False)
    op.create_table('ai_event_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'RETRYING', 'DEAD_LETTER', name='event_status', native_enum=False), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_letter_reason', sa.TEXT(), nullable=True),
    sa.Column('failed_subscriber', sa.String(length=100), nullable=True),
    sa.Column('failed_attempt', sa.Integer(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_event_key', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['ai_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['ai_event_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_event_deliveries_event_id'), 'ai_event_deliveries', ['event_id'], unique=False)
    op.create_index(op.f('ix_ai_event_deliveries_processed_event_key'), 'ai_event_deliveries', ['processed_event_key'], unique=False)
    op.create_index(op.f('ix_ai_event_deliveries_status'), 'ai_event_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_ai_event_deliveries_subscriber_id'), 'ai_event_deliveries', ['subscriber_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_event_deliveries_subscriber_id'), table_name='ai_event_deliveries')
    op.drop_index(op.f('ix_ai_event_deliveries_status'), table_name='ai_event_deliveries')
    op.drop_index(op.f('ix_ai_event_deliveries_processed_event_key'), table_name='ai_event_deliveries')
    op.drop_index(op.f('ix_ai_event_deliveries_event_id'), table_name='ai_event_deliveries')
    op.drop_table('ai_event_deliveries')
    op.drop_index(op.f('ix_ai_events_organization_id'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_event_type'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_correlation_id'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_causation_id'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_aggregate_type'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_aggregate_id'), table_name='ai_events')
    op.drop_table('ai_events')
    op.drop_index(op.f('ix_ai_event_subscriptions_event_type'), table_name='ai_event_subscriptions')
    op.drop_table('ai_event_subscriptions')
    # ### end Alembic commands ###
