"""sprint_5d_multi_agent

Revision ID: a309e0656e77
Revises: ee29a61810fe
Create Date: 2026-07-17 22:59:22.190399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a309e0656e77'
down_revision: Union[str, Sequence[str], None] = 'ee29a61810fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('SALES', 'BUSINESS_ANALYST', 'MARKETING', 'SUPPORT', 'RECRUITER', 'FINANCE', 'HUMAN', name='agent_type', native_enum=False), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('supported_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_parallel_tasks', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_type')
    )
    op.create_table('ai_agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('initiator_agent', sa.Enum('SALES', 'BUSINESS_ANALYST', 'MARKETING', 'SUPPORT', 'RECRUITER', 'FINANCE', 'HUMAN', name='agent_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='session_status', native_enum=False), nullable=False),
    sa.Column('shared_context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shared_context_version', sa.Integer(), nullable=False),
    sa.Column('shared_context_checksum', sa.String(length=64), nullable=True),
    sa.Column('timeline_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('from_agent', sa.Enum('SALES', 'BUSINESS_ANALYST', 'MARKETING', 'SUPPORT', 'RECRUITER', 'FINANCE', 'HUMAN', name='agent_type', native_enum=False), nullable=False),
    sa.Column('to_agent', sa.Enum('SALES', 'BUSINESS_ANALYST', 'MARKETING', 'SUPPORT', 'RECRUITER', 'FINANCE', 'HUMAN', name='agent_type', native_enum=False), nullable=False),
    sa.Column('message_type', sa.Enum('REQUEST', 'RESPONSE', 'EVENT', 'HANDOFF', name='message_type', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('assigned_agent', sa.Enum('SALES', 'BUSINESS_ANALYST', 'MARKETING', 'SUPPORT', 'RECRUITER', 'FINANCE', 'HUMAN', name='agent_type', native_enum=False), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'READY', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'CANCELLED', name='agent_task_status', native_enum=False), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['ai_agent_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_agent_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('workflow_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='session_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_agent_workflows')
    op.drop_table('ai_agent_tasks')
    op.drop_table('ai_agent_messages')
    op.drop_table('ai_agent_sessions')
    op.drop_table('ai_agent_definitions')
    # ### end Alembic commands ###
