"""sprint_4a_execution_enrichment_v2

Revision ID: d32d159ee75a
Revises: cc8b2680cd59
Create Date: 2026-07-13 00:33:28.558781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd32d159ee75a'
down_revision: Union[str, Sequence[str], None] = 'cc8b2680cd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_execution_steps', sa.Column('handler_name', sa.String(length=100), nullable=True))
    op.add_column('workflow_executions', sa.Column('trigger_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('workflow_executions', sa.Column('trigger_type', sa.Enum('LEAD_CREATED', 'LEAD_UPDATED', 'LEAD_STATUS_CHANGED', 'TASK_CREATED', 'TASK_COMPLETED', 'MANUAL', 'API', name='workflow_trigger_type', native_enum=False), nullable=False))
    op.add_column('workflow_executions', sa.Column('trigger_source', sa.String(length=50), nullable=False))
    op.add_column('workflow_executions', sa.Column('execution_mode', sa.String(length=20), nullable=False))
    op.add_column('workflow_executions', sa.Column('condition_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_executions', sa.Column('skipped_reason', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_workflow_executions_request_id'), 'workflow_executions', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_request_id'), table_name='workflow_executions')
    op.drop_column('workflow_executions', 'skipped_reason')
    op.drop_column('workflow_executions', 'condition_trace')
    op.drop_column('workflow_executions', 'execution_mode')
    op.drop_column('workflow_executions', 'trigger_source')
    op.drop_column('workflow_executions', 'trigger_type')
    op.drop_column('workflow_executions', 'trigger_payload')
    op.drop_column('workflow_execution_steps', 'handler_name')
    # ### end Alembic commands ###
