"""sprint_5f_marketing_ai

Revision ID: da0beea601de
Revises: efb0042373f0
Create Date: 2026-07-17 23:35:21.392205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da0beea601de'
down_revision: Union[str, Sequence[str], None] = 'efb0042373f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_audience_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('segment_type', sa.Enum('ALL_LEADS', 'NEW', 'QUALIFIED', 'CUSTOM', 'INACTIVE', 'HIGH_VALUE', name='audience_type', native_enum=False), nullable=False),
    sa.Column('criteria_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_size', sa.Integer(), nullable=False),
    sa.Column('segment_version', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.Enum('EMAIL', 'WHATSAPP', 'MULTI_CHANNEL', 'NEWSLETTER', 'REENGAGEMENT', name='campaign_type', native_enum=False), nullable=False),
    sa.Column('campaign_goal', sa.Enum('LEAD_GENERATION', 'LEAD_NURTURING', 'REENGAGEMENT', 'PRODUCT_LAUNCH', 'UPSELL', 'CROSS_SELL', 'WEBINAR', 'EVENT', name='campaign_goal', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'SCHEDULED', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED', 'FAILED', name='campaign_status', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='campaign_priority', native_enum=False), nullable=False),
    sa.Column('strategy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('campaign_version', sa.Integer(), nullable=False),
    sa.Column('parent_campaign_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_campaign_id'], ['ai_campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_ab_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('variants_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.Column('winner_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'COMPLETED', name='ab_test_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ai_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_campaign_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'SCHEDULED', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED', 'FAILED', name='campaign_status', native_enum=False), nullable=False),
    sa.Column('audience_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statistics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attribution_model', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ai_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['ai_audience_segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_marketing_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('EMAIL', 'WHATSAPP', 'SMS', 'SOCIAL', 'LANDING_PAGE', name='content_type', native_enum=False), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_content_id', sa.UUID(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['ai_approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['ai_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_content_id'], ['ai_marketing_contents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_marketing_contents')
    op.drop_table('ai_campaign_executions')
    op.drop_table('ai_ab_tests')
    op.drop_table('ai_campaigns')
    op.drop_table('ai_audience_segments')
    # ### end Alembic commands ###
