"""sprint_6c_learning

Revision ID: e73028902f64
Revises: 29bed6c8f04f
Create Date: 2026-07-18 19:58:35.478129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e73028902f64'
down_revision: Union[str, Sequence[str], None] = '29bed6c8f04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedback_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_sessions_organization_id'), 'ai_feedback_sessions', ['organization_id'], unique=False)
    op.create_table('ai_improvements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('improvement_type', sa.Enum('PROMPT', 'PLANNER', 'RETRIEVAL', 'POLICY', 'TOOL', 'MEMORY', name='improvement_type', native_enum=False), nullable=False),
    sa.Column('current_version', sa.String(length=50), nullable=False),
    sa.Column('proposed_version', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('pattern_confidence', sa.Float(), nullable=False),
    sa.Column('deployment_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ANALYZED', 'PROPOSED', 'APPROVED', 'DEPLOYED', 'REJECTED', name='suggestion_status', native_enum=False), nullable=False),
    sa.Column('supporting_evaluation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_feedback_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_trace_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_improvements_organization_id'), 'ai_improvements', ['organization_id'], unique=False)
    op.create_table('ai_learning_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('execution_trace_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_id', sa.UUID(), nullable=True),
    sa.Column('feedback_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.Enum('SALES', 'BUSINESS_ANALYST', 'MARKETING', 'SUPPORT', 'RECRUITER', 'FINANCE', 'HUMAN', name='agent_type', native_enum=False), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('dataset_version', sa.Integer(), nullable=False),
    sa.Column('dataset_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['ai_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_trace_id'], ['ai_execution_traces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['ai_feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_learning_datasets_evaluation_id'), 'ai_learning_datasets', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_ai_learning_datasets_execution_trace_id'), 'ai_learning_datasets', ['execution_trace_id'], unique=False)
    op.create_index(op.f('ix_ai_learning_datasets_feedback_id'), 'ai_learning_datasets', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_ai_learning_datasets_organization_id'), 'ai_learning_datasets', ['organization_id'], unique=False)
    op.create_table('ai_policy_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=False),
    sa.Column('current_rule', sa.Text(), nullable=False),
    sa.Column('suggested_rule', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ANALYZED', 'PROPOSED', 'APPROVED', 'DEPLOYED', 'REJECTED', name='suggestion_status', native_enum=False), nullable=False),
    sa.Column('bundle_id', sa.UUID(), nullable=True),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['ai_approvals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_policy_suggestions_organization_id'), 'ai_policy_suggestions', ['organization_id'], unique=False)
    op.create_table('ai_prompt_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('current_prompt', sa.Text(), nullable=False),
    sa.Column('suggested_prompt', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('pattern_confidence', sa.Float(), nullable=False),
    sa.Column('deployment_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ANALYZED', 'PROPOSED', 'APPROVED', 'DEPLOYED', 'REJECTED', name='suggestion_status', native_enum=False), nullable=False),
    sa.Column('estimated_impact', sa.Float(), nullable=True),
    sa.Column('affected_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bundle_id', sa.UUID(), nullable=True),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['ai_approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prompt_suggestions_organization_id'), 'ai_prompt_suggestions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_prompt_suggestions_prompt_id'), 'ai_prompt_suggestions', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_prompt_suggestions_prompt_id'), table_name='ai_prompt_suggestions')
    op.drop_index(op.f('ix_ai_prompt_suggestions_organization_id'), table_name='ai_prompt_suggestions')
    op.drop_table('ai_prompt_suggestions')
    op.drop_index(op.f('ix_ai_policy_suggestions_organization_id'), table_name='ai_policy_suggestions')
    op.drop_table('ai_policy_suggestions')
    op.drop_index(op.f('ix_ai_learning_datasets_organization_id'), table_name='ai_learning_datasets')
    op.drop_index(op.f('ix_ai_learning_datasets_feedback_id'), table_name='ai_learning_datasets')
    op.drop_index(op.f('ix_ai_learning_datasets_execution_trace_id'), table_name='ai_learning_datasets')
    op.drop_index(op.f('ix_ai_learning_datasets_evaluation_id'), table_name='ai_learning_datasets')
    op.drop_table('ai_learning_datasets')
    op.drop_index(op.f('ix_ai_improvements_organization_id'), table_name='ai_improvements')
    op.drop_table('ai_improvements')
    op.drop_index(op.f('ix_ai_feedback_sessions_organization_id'), table_name='ai_feedback_sessions')
    op.drop_table('ai_feedback_sessions')
    # ### end Alembic commands ###
