"""sprint_5c_sales_ai_mvp

Revision ID: ee29a61810fe
Revises: 055695c646d8
Create Date: 2026-07-17 19:12:16.992075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee29a61810fe'
down_revision: Union[str, Sequence[str], None] = '055695c646d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PLANNED', 'EXECUTING', 'WAITING_APPROVAL', 'COMPLETED', 'FAILED', name='planner_state', native_enum=False), nullable=False),
    sa.Column('planner_version', sa.Integer(), nullable=False),
    sa.Column('reasoning_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_action_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('ANALYZE_LEAD', 'CREATE_TASK', 'SEND_EMAIL', 'SEND_WHATSAPP', 'UPDATE_LEAD', 'CHANGE_STATUS', 'REQUEST_APPROVAL', 'WAIT', 'COMPLETE', name='ai_action_type', native_enum=False), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'REJECTED', 'WAITING_APPROVAL', name='ai_action_status', native_enum=False), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_action_id'], ['ai_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['ai_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('requested_to', sa.UUID(), nullable=True),
    sa.Column('approval_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='ai_approval_status', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['ai_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_to'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_approvals')
    op.drop_table('ai_actions')
    op.drop_table('ai_plans')
    # ### end Alembic commands ###
