"""sprint_5e_business_ai

Revision ID: efb0042373f0
Revises: a309e0656e77
Create Date: 2026-07-17 23:18:30.051579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb0042373f0'
down_revision: Union[str, Sequence[str], None] = 'a309e0656e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_kpi_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_kpi_definitions_name'), 'ai_kpi_definitions', ['name'], unique=True)
    op.create_table('ai_business_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'CUSTOM', name='business_report_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_report_id', sa.UUID(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_report_id'], ['ai_business_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('forecast_period', sa.Enum('F_7_DAYS', 'F_30_DAYS', 'F_90_DAYS', 'F_180_DAYS', name='forecast_period', native_enum=False), nullable=False),
    sa.Column('predicted_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('predicted_conversion_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('forecast_model', sa.String(length=100), nullable=False),
    sa.Column('forecast_version', sa.Integer(), nullable=False),
    sa.Column('training_period', sa.String(length=100), nullable=True),
    sa.Column('assumptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forecast_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_kpi_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('qualified_leads', sa.Integer(), nullable=False),
    sa.Column('won_deals', sa.Integer(), nullable=False),
    sa.Column('lost_deals', sa.Integer(), nullable=False),
    sa.Column('pipeline_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('average_sales_cycle', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('average_response_time', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('calculation_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='recommendation_priority', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('recommended_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELEGATED', 'DISMISSED', name='recommendation_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_recommendations')
    op.drop_table('ai_kpi_snapshots')
    op.drop_table('ai_forecasts')
    op.drop_table('ai_business_reports')
    op.drop_index(op.f('ix_ai_kpi_definitions_name'), table_name='ai_kpi_definitions')
    op.drop_table('ai_kpi_definitions')
    # ### end Alembic commands ###
